export const goblinArray = [
    {
        name: 'George',
        hp: Math.ceil(Math.random() * 4),
        image: './assets/enemies/enemy-1.jpeg',
        id: undefined,
        alive: true,
    }, 
    {
        name: 'Fred',
        hp: Math.ceil(Math.random() * 4),
        image: './assets/enemies/enemy-2.jpeg',
        id: undefined,
        alive: true,
    },
    {
        name: 'Billy',
        hp: Math.ceil(Math.random() * 4),
        image: './assets/enemies/enemy-3.jpeg',
        id: undefined,
        alive: true,
    },
    {
        name: 'Bob',
        hp: Math.ceil(Math.random() * 4),
        image: './assets/enemies/enemy-4.jpeg',
        id: undefined,
        alive: true,
    },
    {
        name: 'Courage',
        hp: Math.ceil(Math.random() * 4),
        image: './assets/enemies/enemy-5.jpeg',
        id: undefined,
        alive: true,
    },
    {
        name: 'Thug life',
        hp: Math.ceil(Math.random() * 4),
        image: './assets/enemies/enemy-6.jpeg',
        id: undefined,
        alive: true,
    },
    {
        name: 'Jerk face',
        hp: Math.ceil(Math.random() * 4),
        image: './assets/enemies/enemy-7.jpeg',
        id: undefined,
        alive: true,
    },
    {
        name: 'Punch head',
        hp: Math.ceil(Math.random() * 4),
        image: './assets/enemies/enemy-8.jpeg',
        id: undefined,
        alive: true,
    },
    {
        name: 'Sir sure',
        hp: Math.ceil(Math.random() * 4),
        image: './assets/enemies/enemy-9.jpeg',
        id: undefined,
        alive: true,
    },
    {
        name: 'Big Daddy',
        hp: Math.ceil(Math.random() * 4),
        image: './assets/enemies/enemy-10.jpeg',
        id: undefined,
        alive: true,
    }
];